customCommands:
  - key: 'O'
    description: 'Open file in nvim buffer'
    context: 'files'
    command: 'nvim --server "$NVIM" --remote-expr "luaeval(\"lazygit_open_file(_A)\", \"{{.SelectedFile.Name}}\")"'
